### Diabetes Prediction Model ANN using Deep Learning

### Importing Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

### Loading Dataset

In [2]:
data=pd.read_csv("diabetes.csv")
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [33]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

### Declaring dependent and independent variables

In [34]:
x=data.iloc[:, 0:-1].values
y=data.iloc[:, -1].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [35]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

### No encoding required as all dataset attributes/ fields are in numeric type

### Splitting dataset into training and testing sets

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

### Feature Scaling of required fields/attributes

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [38]:
X_train

array([[-0.52639686, -1.15139792, -3.75268255, ..., -4.13525578,
        -0.49073479, -1.03594038],
       [ 1.58804586, -0.27664283,  0.68034485, ..., -0.48916881,
         2.41502991,  1.48710085],
       [-0.82846011,  0.56687102, -1.2658623 , ..., -0.42452187,
         0.54916055, -0.94893896],
       ...,
       [ 1.8901091 , -0.62029661,  0.89659009, ...,  1.76054443,
         1.981245  ,  0.44308379],
       [-1.13052335,  0.62935353, -3.75268255, ...,  1.34680407,
        -0.78487662, -0.33992901],
       [-1.13052335,  0.12949347,  1.43720319, ..., -1.22614383,
        -0.61552223, -1.03594038]])

### Building the ANN

### Initialising the ANN

In [50]:
model=tf.keras.models.Sequential()

### Adding input layer

In [51]:
model.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [52]:
model.add(tf.keras.layers.Dense(units=5, activation='relu'))

In [53]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN model

In [54]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN model with training dataset

In [55]:
X_train.shape

(614, 8)

In [56]:
model.fit(X_train, y_train, batch_size=8, epochs=25)

Epoch 1/25
77/77 [==============================] - 1s 3ms/step - loss: 0.6865 - accuracy: 0.6254
Epoch 2/25
77/77 [==============================] - 0s 3ms/step - loss: 0.6625 - accuracy: 0.6678
Epoch 3/25
77/77 [==============================] - 0s 3ms/step - loss: 0.6410 - accuracy: 0.6889
Epoch 4/25
77/77 [==============================] - 0s 3ms/step - loss: 0.6195 - accuracy: 0.7003
Epoch 5/25
77/77 [==============================] - 0s 3ms/step - loss: 0.5967 - accuracy: 0.7117
Epoch 6/25
77/77 [==============================] - 0s 4ms/step - loss: 0.5748 - accuracy: 0.7199
Epoch 7/25
77/77 [==============================] - 0s 3ms/step - loss: 0.5539 - accuracy: 0.7329
Epoch 8/25
77/77 [==============================] - 0s 3ms/step - loss: 0.5354 - accuracy: 0.7541
Epoch 9/25
77/77 [==============================] - 0s 3ms/step - loss: 0.5182 - accuracy: 0.7590
Epoch 10/25
77/77 [==============================] - 0s 3ms/step - loss: 0.5035 - accuracy: 0.7638
Epoch 11/25
77/77 [

### Making the prediction and evaluationg the model

In [57]:
y_pred=model.predict(X_test)

5/5 [==============================] - 0s 4ms/step


In [58]:
y_pred=(y_pred>0.5)

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred)
cm

array([[85, 14],
       [19, 36]], dtype=int64)

In [60]:
accuracy_score(y_test, y_pred)

0.7857142857142857

### -Made by Manish Kumar